Support byte constants
FabricMC/unpick pull request #5
Opened 2021-04-01 19:58 UTC by modmuss50

As far as I can tell its safe enough to pass this down the int path in InstructionFactory. Seems to work ok.

Also makes missing constants a fatal error.

2021-04-01 20:46 UTC, Earthcomputer requested changes
A few things that should probably be fixed:
1. If we add support for bytes, why not add support for shorts too?
2. The `FlagDefinition` class only allows for ints and longs, should probably be fixed to allow for any integral type.
3. `FlagConstantGroup` also checks for ints and longs.

2021-04-01 20:47 UTC, modmuss50 commented
Yeah, that all sounds resonable, going to add some unit tests for it as well 👍

2021-04-02 00:32 UTC, liach commented
How about supporting short and char? They are both int in the instructions

2021-04-02 11:39 UTC, Earthcomputer commented
I just noticed that this PR only adds `Byte` to `LiteralType` and not `IntegerType`

2021-04-06 13:13 UTC, liach commented
Yeah, a few comments from me:
1. Add byte and short to integer type (can be used as bit flags, mainly byte is used in entity data tracker)
2. Add byte, short, char, (and a few other primitives) to literal types. Namely everything that can appear in the javadoc constant value page should be accepted.

2021-04-08 09:38 UTC, closed without merging